# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            GH
tagline:          'A Jekyll theme'
description:      ''
url:              https://xnoxy7.github.io
baseurl:          ""

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
